language: go
go:
- 1.6.4
- 1.7.4
sudo: false
install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/labstack/echo
  - go get github.com/gin-gonic/gin
  - go get github.com/gorilla/mux
  - go get github.com/julienschmidt/httprouter
